{% set name = "pycraf-gui" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycraf-gui-{{ version }}.tar.gz
  sha256: 5f52b9208b145d4a86cf88c21814cece65d7917831a6c6889d460bf95ad6f318

build:
  entry_points:
    - pycraf-gui = pycraf_gui.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=30.3.0
    - setuptools_scm >=6.2

  run:
    - python >={{ python_min }}
    - astropy
    - numpy
    - matplotlib >=3
    - pycraf
    - pyqt >=5
    - pytest
    - pytest-astropy
    - pytest-qt

test:
  imports:
    - pycraf_gui
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bwinkel/pycraf-gui
  summary: A simple GUI for pycraf
  description: |
    The pycraf package provides functions and procedures for various tasks in spectrum-management compatibility studies. This package, pycraf-gui
    provides a simple user interface for the path attenuation functionality of pycraf.
  dev_url: https://github.com/bwinkel/pycraf-gui
  license: GPL-3.0-only
  license_file:
    - COPYING
    - TEMPLATE_LICENCE.rst

extra:
  recipe-maintainers:
    - bwinkel
